kind: pipeline
name: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: s3-cache
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-s3-cache:1.0
    settings:
      restore: true
      mount:
        - ./.git
        - ./.yarn-local-mirror
        - ./node_modules
        - ./packages/*/node_modules
        - ./test/plugin_functional/plugins/*/node_modules
        - ./test/interpreter_functional/plugins/*/node_modules
      endpoint: https://cache.wodcloud.com
      access_key:
        from_secret: ACCESS_KEY_MINIO
      secret_key:
        from_secret: SECRET_KEY_MINIO

  - name: fetch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    settings:
      proxy:
        from_secret: SOCKS5_PROXY

  - name: node
    image: registry.cn-qingdao.aliyuncs.com/wod-arm/opensearch-dashboards-build:v1.x
    environment:
      BUILD_VERSION: 1.3.5
    commands:
      - yarn osd bootstrap --allow-root
      - git apply .beagle/v1.3-i18n-zh-CN.patch
      - export YARN_CACHE_FOLDER=$PWD/.yarn-local-mirror/
      - yarn build-platform --skip-os-packages --skip-archives --linux --linux-arm

  - name: dumb-init-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/dumb-init:v1.2.5-amd64
    commands:
      - mkdir -p ./build/dumb-init
      - cp /bin/dumb-init ./build/dumb-init/dumb-init-linux-x64-v1.2.5

  - name: dumb-init-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/dumb-init:v1.2.5-arm64
    commands:
      - mkdir -p ./build/dumb-init
      - cp /bin/dumb-init ./build/dumb-init/dumb-init-linux-arm64-v1.2.5

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/opensearch-dashboards/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bookworm-slim-amd64
      repo: wod/opensearch-dashboards
      version: v1.4.0
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=x64,TARGEVERSION=1.3.5,BUILD_DATE=$(date),BUILD_REVISION=$CI_COMMIT_SHA'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/opensearch-dashboards/dockerfile
      base: registry.cn-qingdao.aliyuncs.com/wod/debian:bookworm-slim-arm64
      repo: wod/opensearch-dashboards
      version: v1.4.0
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64,TARGEVERSION=1.3.5,BUILD_DATE=$(date),BUILD_REVISION=$CI_COMMIT_SHA'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry.cn-qingdao.aliyuncs.com/wod/opensearch-dashboards:v1.4.0-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/opensearch-dashboards:v1.4.0
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: pipeline
name: harbor

trigger:
  branch:
    - master

platform:
  runner: 10.11.92.33

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

clone:
  disable: true

steps:
  - name: harbor-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/opensearch-dashboards:v1.4.0-amd64
      target: registry.cn-qingdao.aliyuncs.com/wod/opensearch-dashboards:v1.4-amd64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      source: registry.cn-qingdao.aliyuncs.com/wod/opensearch-dashboards:v1.4.0-arm64
      target: registry.cn-qingdao.aliyuncs.com/wod/opensearch-dashboards:v1.4-arm64
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

  - name: harbor-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64
      template: registry.cn-qingdao.aliyuncs.com/wod/opensearch-dashboards:v1.4-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/opensearch-dashboards:v1.4
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN

---
kind: secret
name: SOCKS5_PROXY
get:
  name: SOCKS5_PROXY
  path: devops-secrets

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  name: REGISTRY_USER_ALIYUN
  path: devops-secrets

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  name: REGISTRY_PASSWORD_ALIYUN
  path: devops-secrets

---
kind: secret
name: ACCESS_KEY_MINIO
get:
  name: ACCESS_KEY_MINIO
  path: devops-secrets

---
kind: secret
name: SECRET_KEY_MINIO
get:
  name: SECRET_KEY_MINIO
  path: devops-secrets
